### PR TITLE
Fix trade action behavior on a specific account

### LINKED ISSUE #35: Using the trade action on any specific account other than the first one doesn't work
When using the `trade` action on any specific account which isn't the first one in `SteamGuardAccounts` the program exits early without processing its confirmations. The issue is in this `foreach` loop https://github.com/dyc3/steamguard-cli/blob/042b2acf763cc5aadc418cc4609033315f19f203/Program.cs#L539-L546
This means that it's only possible to specifically use the `trade` action on the first loaded account or iterate through all of them.
I'll submit a PR with a fix soon.

### PR DESCRIPTION
**Pull request by amdev0**
Fix #35

### CODE REVIEW

File: Program.cs [hunk 1]
```diff
@@ -538,11 +538,10 @@ static void Trade(string user = "", string passkey = "")
 
 			foreach (var account in SteamGuardAccounts)
 			{
-				if (user != "")
-					if (!string.Equals(account.AccountName, user, StringComparison.CurrentCultureIgnoreCase))
-						break;
```
Comment (dyc3) [inline Program.cs]: I think just changing this line to a `continue` would suffice.

Comment (amdev0) [reply Program.cs]: That would work too, it's up to you. I took a look at how `accept-all` was implemented and just did something similar because I personally don't like using `continue` unless necessary.
